# Generated by Django 3.2.15 on 2022-12-13 10:28

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='photo',
            field=models.ImageField(null=True, upload_to='cover', validators=[catalog.models.BookInstance.validate_image], verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookFile',
            field=models.FileField(null=True, upload_to=' ', verbose_name='Файл с книгой'),
        ),
    ]
